glances/outputs/static/css/style.css, glances/outputs/static/html/stats.html
Changes : 
* use em instead of px
* the dots animation is now visible even on small devices
* add link to provide initial source of the animation
=> Improve rendering of the Web UI loading page on small devices

glances/outputs/static/css/style.css
Changes : 
* align columns name and command to left
* avoid text wrap
=> Better rendering for docker plugin on web UI

glances/core/glances_autodiscover.py, glances/core/glances_client_browser.py, glances/core/glances_processes.py, glances/outputs/static/html/stats.html
=> [Web UI] Display the Docker plugin only if there is a running container

conf/glances.conf, docs/glances-doc.rst, glances/core/glances_main.py, glances/exports/glances_rabbitmq.py, man/glances.1
Hope all is good :) 
Export to RabbitMQ in python 2.7 and 3.4
Add informations in manpage and rst ! 
Katyucha
=> RabbitMQ export (3rd try)

glances/outputs/static/html/plugins/alert.html, glances/outputs/static/js/stats_controller.js
=> [Web UI] Fix formatting of date/time in Alert plugin

MANIFEST.in
Add HTML and images files for the web UI in the MANIFEST
=> Fix MANIFEST for the web UI

glances/outputs/static/js/filters.js
=> [Web UI] Fix question mark display instead of zero as nice level in process list

glances/outputs/static/html/plugins/processlist.html
=> [Web UI] Remove decoration on processes which are not running

glances/outputs/static/html/plugins/mem.html, glances/outputs/static/html/plugins/mem_more.html, glances/outputs/static/html/plugins/memswap.html, glances/outputs/static/html/plugins/processlist.html, glances/outputs/static/js/filters.js
=> [Web UI] Fox conversion issue of bytes/bites

glances/outputs/static/html/plugins/diskio.html
=> [Web UI] Order disk by name

glances/outputs/static/html/plugins/load.html
=> [Web UI] Round load values

glances/outputs/static/html/plugins/system.html, glances/outputs/static/html/stats.html
=> [Web UI] Fix system and IP infos

glances/exports/glances_influxdb.py
=> Fix influxdb export for 0.8.

glances/exports/glances_influxdb.py
Reverts nicolargo/glances#580
Included in the DEVELOP branch.
=> Revert "Fix influxdb export for 0.8."

glances/outputs/static/html/plugins/cpu_more.html, glances/outputs/static/html/plugins/mem_more.html
=> [Web UI] Regression with the CPU plugin: IOWait, IRQ, Steal do not displayed anymore

glances/outputs/static/html/plugins/processlist.html, glances/outputs/static/html/plugins/system.html, glances/outputs/static/js/stats_controller.js
=> [Web UI] Highlight nice values

glances/outputs/static/js/stats_controller.js
=> [Web UI] Use limits to highlight the values

glances/outputs/static/css/style.css, glances/outputs/static/html/plugins/processlist.html, glances/outputs/static/js/filters.js, glances/outputs/static/js/stats_controller.js
=> [Web UI] Fix format of time+ in the process list

glances/outputs/static/css/style.css, glances/outputs/static/html/plugins/sensors.html, glances/outputs/static/html/stats.html
=> [Web UI] Sidebar display problem

glances/outputs/static/html/plugins/cpu.html, glances/outputs/static/html/plugins/cpu_more.html, glances/outputs/static/html/plugins/fs.html, glances/outputs/static/html/plugins/load.html, glances/outputs/static/html/plugins/mem.html, glances/outputs/static/html/plugins/memswap.html, glances/outputs/static/html/plugins/processlist.html, glances/outputs/static/html/plugins/sensors.html, glances/outputs/static/js/stats_controller.js
Fix #587 
The current current way of managing limits/alerts do not take into account the "maximum" in calculations.
So I refactored the method to be closer to what is done in python https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_plugin.py#L352
=> [Web UI] Load limit take Core number into account

glances/outputs/static/html/plugins/cpu.html, glances/outputs/static/html/plugins/per_cpu.html, glances/outputs/static/html/stats.html
=> [Web UI] Improve per cpu plugin

glances/outputs/static/js/stats_controller.js
=> [Web UI] Remove empty battery

glances/core/glances_main.py, glances/outputs/glances_bottle.py
Related to #446
Todo : 
Update doc
=> [WIP] Add authentication to the Web server

glances/outputs/static/html/help.html
=> [Web UI] Help page responsive on small screen

glances/outputs/static/html/plugins/system.html, glances/outputs/static/js/stats_controller.js
=> [Web UI] Warn user if the server is down/disconnected

glances/outputs/static/js/services/plugins/glances_sensors.js
=> Hide empty sensors in web ui

glances/outputs/static/html/help.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/stats_controller.js
* remove all shortcuts not implemented yet in web UI
* implement show/hide Docker stats shortcut
* implement show/hide processes stats shortcut
* update help page
Fix #554.
=> [Web UI] Update keyboard shortcuts

glances/outputs/static/html/stats.html
=> [Web UI] Reorder top plugins like in the curse interface

glances/outputs/static/js/services/plugins/glances_memswap.js
=> [Web UI] Fix memswap plugin displaying mem values

glances/outputs/static/html/help.html, glances/outputs/static/html/plugins/fs.html, glances/outputs/static/js/stats_controller.js
=> [WebUI] filesystem free space

glances/outputs/static/html/index.html, glances/outputs/static/html/plugins/raid.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/services/core/glances_stats.js, glances/outputs/static/js/services/plugins/glances_raid.js, glances/outputs/static/js/stats_controller.js
The PR adds the raid plugin to the WebUI.
Result of my current implementation: 
See issue #552
=> [WIP][WebUI] RAID Plugin

glances/outputs/static/css/style.css, glances/outputs/static/html/plugins/monitor.html, glances/outputs/static/js/services/plugins/glances_monitor.js
=> [Web UI] Truncate long message in monitor plugin

glances/outputs/static/html/plugins/alert.html
Curse : 
WebUI before : 
WebUI after :
=> [WebUI] when alert is ongoing hide level

glances/outputs/static/html/plugins/processlist.html, glances/outputs/static/js/services/plugins/glances_processlist.js
Curse :
WebUI before :
WebUI after :
=> [WebUI] hide io read/write if value is not present

index.html
=> Developers Typo

glances/outputs/static/css/style.css, glances/outputs/static/js/directives.js
Add a "pointer" cursor to indicate which columns are sortable
=> [WebUI] add "pointer" cursor for sortable columns

glances/outputs/static/html/plugins/processlist.html
=> [Web UI] Fix processlist IO cells not displayed

glances/outputs/static/js/services/plugins/glances_processlist.js
=> [Web UI] Fix no nice decoration in processlist

glances/outputs/static/js/services/plugins/glances_processlist.js
=> [WebUI] fixe display of nice on windows

glances/outputs/static/html/index.html, glances/outputs/static/js/app.js, glances/outputs/static/js/stats_controller.js
See #724
Result : 
```<hostname> - Glances```
=> [WebUI] Use hostname for title

glances/plugins/glances_docker.py
=> Fix unable to find version in docker api error exception parsing

.travis.yml
Travis has a new feature (in beta) which allows to run test under linux and osx :
https://docs.travis-ci.com/user/multi-os/
=> [WIP] Use Travis multi os feature

glances/webserver.py
=> Fix hddtemp not displayed in web ui

glances/plugins/glances_diskio.py
=> Fix hide interface config not take into account in web ui

glances/outputs/static/js/services/plugins/glances_alert.js
Fix bug "Cannot read property 'length' of undefined" of #687
=> [WebUI] check if alerts is empty

glances/outputs/static/html/help.html, glances/outputs/static/html/plugins/diskio.html, glances/outputs/static/js/services/plugins/glances_diskio.js, glances/outputs/static/js/stats_controller.js
=> [WebUI] Add IOps in the DiskIO plugin

glances/outputs/glances_curses.py
=> Fix show/hide top menu

glances/outputs/glances_curses.py
In my last PR (#773), I forgot to remove one of my debug.
=> Remove useless debug

glances/plugins/glances_processlist.py, glances/processes.py
See https://github.com/nicolargo/glances/issues/546#issuecomment-175272479
This reverts commit eee6dd6dbfa4bca38bda11602175a34e2fc046bc, reversing
changes made to dbb97a53442751ce8e653a6042037f7f1c881803.
=> Revert "Merge pull request #786 from desbma/develop"

glances/main.py, glances/outputs/glances_bottle.py, glances/outputs/static/html/index.html, glances/outputs/static/html/plugins/diskio.html, glances/outputs/static/html/plugins/fs.html, glances/outputs/static/html/plugins/network.html, glances/outputs/static/html/plugins/processlist.html, glances/outputs/static/html/plugins/quicklook.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/app.js, glances/outputs/static/js/services/core/glances_stats.js, glances/outputs/static/js/stats_controller.js
The arguments are now taken into account in the WebUI.
Fix #784
=> [WebUI] Use arguments

glances/outputs/static/html/stats.html
=> [WebUI] hide diskio when no data

AUTHORS
Thanks @nicolargo for the mention/addition :)
=> authors: Update Debian link for Glances package (use tracker.d.o)

index.html
http://glances.readthedocs.org/en/latest/glances-doc.html returns
a 404 - Not Found
=> Fix the link to the documentation

AUTHORS
Adds me as the conda package maintainer (conda-forge).
=> Add conda package maintainer (conda-forge)

glances/outputs/static/css/style.css, glances/outputs/static/html/plugins/quicklook.html, glances/outputs/static/js/services/plugins/glances_quicklook.js
=> [Web UI] add cpu name in quicklook plugin

glances/outputs/static/html/plugins/folders.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/services/core/glances_stats.js, glances/outputs/static/js/services/plugins/glances_folders.js, glances/outputs/static/js/stats_controller.js
Fix an error describe in this [comment](https://github.com/nicolargo/glances/issues/721#issuecomment-158617635). The plugin was correctly implemented but due to a bug, it could not be displayed.
* Bug fix: yes
* Fixed tickets: #721
=> [Web UI] Fix folders plugin never displayed

glances/outputs/static/js/services/plugins/glances_folders.js
Fix issue describe [here](https://github.com/nicolargo/glances/issues/828#issuecomment-202551162).
Before: 
After:
* Bug fix: yes
* Related tickets: #828
=> [Web UI] Fix folder plugin decoration issue for exclamation/question mark

glances/outputs/static/html/plugins/ip.html, glances/outputs/static/js/services/plugins/glances_ip.js
* Bug fix: no
* Fixed tickets: #646
=> [Web UI] Add public IP address

glances/outputs/static/js/services/plugins/glances_processlist.js
=> [Web UI] Fix process long command line displayed as array

glances/outputs/static/js/services/plugins/glances_processlist.js
* Bug fix: yes
* Fixed tickets: #839
=> [Web UI] Fix process list sometimes not display on firefox

glances/plugins/glances_processlist.py
See https://github.com/nicolargo/glances/issues/849#issuecomment-212142618
=> Fix #849 - part 2

glances/outputs/static/html/help.html, glances/plugins/glances_help.py
* Bug fix: no
* Related tickets: #780
=> Add new amp shortcut 'A' on help page

glances/outputs/static/html/plugins/diskio.html, glances/outputs/static/js/services/plugins/glances_diskio.js
* Bug fix: yes
* Related tickets: #882
=> [Web UI] handle aliases in diskio plugin

glances/outputs/static/html/index.html, glances/outputs/static/html/plugins/ports.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/filters.js, glances/outputs/static/js/services/core/glances_stats.js, glances/outputs/static/js/services/plugins/glances_amps.js, glances/outputs/static/js/services/plugins/glances_ports.js, glances/outputs/static/js/stats_controller.js
* Bug fix: no
* Fixed tickets: #734
=> [Web UI] add ports plugin

glances/outputs/static/html/help.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/stats_controller.js, glances/plugins/glances_help.py
* Bug fix: yes
* Related tickets: #734
=> Ports plugin keyboard shortcut

glances/outputs/static/js/services/plugins/glances_raid.js, glances/outputs/static/public/css/style.css, glances/outputs/static/public/js/main.js, glances/outputs/static/public/js/vendor.js
Fix loading of the raid plugin in the web UI.
* Bug fix: yes
* Fixed tickets: #934
=> Fix loading of the raid plugin in the web UI

glances/main.py, glances/outputs/static/html/stats.html, glances/outputs/static/js/stats_controller.js, glances/outputs/static/public/js/main.min.js, glances/outputs/static/public/stats.html
Fixes missed renames of args and options
* Bug fix: yes
* Fixed tickets: #956
=> Fix issue #956

glances/outputs/static/html/help.html, glances/outputs/static/html/stats.html, glances/outputs/static/js/controllers.js, glances/outputs/static/public/help.html, glances/outputs/static/public/js/main.min.js, glances/outputs/static/public/js/vendor.min.js, glances/outputs/static/public/stats.html, glances/plugins/glances_help.py
Add missing keyboard shortcuts for gpu plugin in curse and web UI interfaces. 
* Bug fix: yes
* Related tickets: #170
=> add gpu plugin shortcuts

glances/plugins/glances_docker.py
add url npipe:////./pipe/docker_engine for plugin docker if glances run on windows
* Fixed tickets: issue#1009
=> issue#1009

glances/main.py, glances/outputs/glances_bottle.py
Reverts nicolargo/glances#1098
=> Revert "add option to change default username and realm"

docs/aoa/amps.rst
Add link to config
* Bug fix: no
=> Add link to config

glances/plugins/glances_diskio.py, glances/plugins/glances_network.py, glances/plugins/glances_plugin.py
The same as PR #1229 but for networks.
* Bug fix: no
=> Use alias aware sorting also for network devices

unitest.py
Tests whether the method correctly sorts numbers and aliases.
* Bug fix: no
=> Add a unit test for plugin's sorted stats method

glances/main.py, glances/outputs/glances_bottle.py
The WebUI now use the default refresh time if the value < 1.
* Bug fix: yes
* Fixed tickets: #1241
=> Fix WebUI when refresh_time is negative

setup.py
Fix a bug with pip installs on python3 related to nvidia-ml-py3
* Bug fix: yes
* Fixed tickets:  #1273
=> Use nvidia-ml-py3 for python3 compatibility

README.rst
* Bug fix: no
* New feature:no
* Fixed tickets: -
**Added alternative Python installation method**
=> Added alternative Python installation method

conf/glances.conf, docs/gw/index.rst, docs/gw/mqtt.rst, glances/README.txt, glances/exports/glances_mqtt.py, optional-requirements.txt, setup.py
Initial support for exporting data to a MQTT server
* Bug fix: no
=> Support for exporting data to a MQTT server

docker-files/devel-arm/Dockerfile
Fixes #1320 
Tested on Rock64 board
* Fixed tickets: #1320
=> Fix Docker ARM build

glances/outputs/glances_curses_browser.py
Browsing with Up/Down/PageUp/PageDown key.
curses-browser can navigate with server list page. 
* Bug fix: no
=> curses-browser's server list paging added.

glances/exports/glances_kafka.py
fix mistake in comment 
The comment use cassandra instead of kafka
* Bug fix: no
=> fix mistake in comment

snap/snapcraft.yaml
Refer to each commit message for details.
The comparison of the version string style:
```
channels:                                      
beta:      2.11.1                  (5)  10MB -
edge:      v3.1.0+git31.38706c9    (61) 11MB -
installed:   3.1.0-30-g42d1142-dirty (x2) 10MB -
```
* Bug fix: yes
=> Improve snap version generation and introducing metadata sharing with setuptools

glances/exports/glances_elasticsearch.py
Renames utc_timestamp to timestamp
* Bug fix: yes
=> switch back to timestamp el name, clean up verbiage

snap/local/launchers/glances-launch, snap/snapcraft.yaml
This PR supports canonical config paths by the help of the
`personal-files` and the `system-files` security confinement interfaces.
Signed-off-by: 林博仁(Buo-ren Lin) <Buo.Ren.Lin@gmail.com>
* Bug fix: kinda
* New feature: kinda
* Fixed tickets: #1403
=> snap: Support canonical config paths, fixes #1403

snap/snapcraft.yaml
Refer each commit for more information.
* Bug fix: no
* New feature: kinda
* Fixed tickets: N/A
=> snap: general improvements

glances/plugins/glances_docker.py
Don't print errors to the console when docker restarts.  Instead, loss of connection to the daemon should stop the threads and clear out current version and container lists.
* Bug fix: yes
* Fixed tickets: #1428 (guessing given the limited information in the issue)
=> Improve error handling when docker restarts

MANIFEST.in, setup.py
Fixes error during `python3 setup.py install`. Bug was introduced in b43b5007a92e75f474fb967e1a40912abd25468e.
* Bug fix: yes
=> Fix missing file during install

.travis.yml
- do not use "sudo" keyword
cf.
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
- do not use "python setup.py install" any more - prefer pip
modified:   .travis.yml
Update travis config file.
=> Modernize travis config file.

glances/amps/glances_default.py, glances/amps/glances_nginx.py, glances/amps/glances_systemd.py, glances/amps/glances_systemv.py, glances/config.py, glances/outputs/glances_curses.py, glances/plugins/glances_ports.py
Fixes below warnings using raw strings and !=. Fixes `isAlive` attribute error.
```
./glances/config.py:108: DeprecationWarning: invalid escape sequence \`
self.re_pattern = re.compile('(\`.+?\`)')
./glances/outputs/glances_curses.py:700: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if p is not 'load':
./glances/amps/glances_systemd.py:20: DeprecationWarning: invalid escape sequence \/
"""
./glances/amps/glances_systemv.py:20: DeprecationWarning: invalid escape sequence \/
"""
./glances/amps/glances_nginx.py:20: DeprecationWarning: invalid escape sequence \/
"""
./glances/amps/glances_default.py:20: DeprecationWarning: invalid escape sequence \/
"""
```
* Bug fix: yes
* Fixed tickets: #1585
=> Fix warnings and improve Python 3.9 compatibility.

glances/main.py, glances/outputs/glances_curses.py
We can have glances working on windows in console mode - there is windows-curses module which works pretty great, snip from w10 with pip installed windows-curses:
=> glances can work in console mode on windows - windows-curses

.ci/appveyor/download_exes.py, .travis.yml, appveyor.yml, setup.py, tox.ini
Add python 3.7 and 3.8 into CI.
Relates to https://github.com/Homebrew/homebrew-core/pull/52149
=> Add python 3.7 and 3.8 into CI

README.rst
https://github.com/termux/termux-packages/issues/4151
Clean documentation
* Bug fix: no
=> Not need for python-dev anymore

conf/glances-grafana.json
The current json only works if the prefix is localhost.
Signed-off-by: Paulo Flabiano Smorigo <pfsmorigo@gmail.com>
This commit will use the host selected in the combobox at the top of the page.
* Bug fix: yes
* Fixed tickets: N/A
=> Fix grafana json

glances/exports/glances_rabbitmq.py
This pull request adds amqps protocol support for rabbitmq export
* Bug fix: no
* Fixed tickets: #1687
=> Add amqps protocol suppport for rabbitmq export

optional-requirements.txt
All base requirement packages to be install via optional-requirements
* Bug fix: no
=> added optional requirements

glances/outputs/glances_curses.py
Manual refresh of stats on F5 keypress 
* Fixed tickets: #1616 
So far no documentation updates, I will update if maintainers are happy with the code.
=> manual refresh on F5

docker-compose/Dockerfile, docker-compose/docker-compose.yml, docker-compose/glances.conf
=> 提交docker-compose文件

.github/workflows/main.yml, docker-files/dev.Dockerfile
Update pipeline to build dev image with all optional requirements.
Requires base image to be full fledged debian python -> results in bigger image size for dev.
* Bug fix: no
* Fixed tickets: fix #1757, fix #1751
=> fix: docker dev build contains all optional requirements

.github/workflows/main.yml, docker-files/dev.Dockerfile
- Fix release scripts
- Use better caching for docker builds
* Bug fix: no
=> ci: fix release process and improve build speeds

.github/workflows/main.yml
- Readds support for docker armv6
- fix releasing for dev build
* Bug fix: no
=> Readd armv6 docker image

docs/gw/mqtt.rst, glances/exports/glances_mqtt.py
Provides an option to change the MQTT topic structure to reduce the number of messages sent.
* Bug fix: no
* Fixed tickets: #1798
=> Add option for alternate MQTT topic structure

glances/exports/glances_json.py
The file descriptor have nothing ot close it then the Write is consider as a append
* Bug fix: yes
* Fixed tickets: #1814
=> Fixe issue #1814

glances/main.py
Fix documentation typo.
* Bug fix: no
=> Fix typo in documentation

glances/compat.py
=> fixed typo in comments

docker-files/alpine.Dockerfile
The correct one of #1896. 
Sorry for breaking 3.2.2
* Bug fix: yes
=> Fix alpine path

glances/plugins/glances_docker.py
Fix the networks stats being displayed due to the typo. The PR also includes some typo fixes for comments and minor changes like removing an unused import.
* Bug fix: yes
* Fixed tickets: #1943 and #1918 (partially)
=> Bug Fix: Docker plugin - Network stats not being displayed

conf/glances-grafana.json
It had a specific host, with this fix it will work for all hosts
* Bug fix: yes
=> Fix Grafana CPU temperature panel

glances/plugins/glances_docker.py
Updates to the docker plugin to reduce some minor repeated computation. Renaming variables. Removal of legacy comments
* Bug fix: No
* New feature: No
=> Docker plugin updates

glances/amps/glances_amp.py, glances/amps/glances_default.py, glances/amps/glances_nginx.py, glances/amps/glances_systemv.py, glances/exports/glances_cassandra.py, glances/exports/glances_couchdb.py, glances/exports/glances_csv.py, glances/exports/glances_elasticsearch.py, glances/exports/glances_export.py, glances/exports/glances_graphite.py, glances/exports/glances_influxdb.py, glances/exports/glances_influxdb2.py, glances/exports/glances_kafka.py, glances/exports/glances_mqtt.py, glances/exports/glances_opentsdb.py, glances/exports/glances_rabbitmq.py, glances/exports/glances_restful.py, glances/exports/glances_riemann.py, glances/exports/glances_statsd.py, glances/exports/glances_zeromq.py, glances/outputs/glances_bars.py, glances/outputs/glances_curses.py, glances/outputs/glances_curses_browser.py, glances/outputs/glances_sparklines.py, glances/outputs/glances_stdout.py, glances/outputs/glances_stdout_apidoc.py, glances/outputs/glances_stdout_csv.py, glances/outputs/glances_stdout_issue.py
Clean up for doc-strings that don't match the convention specified and typo/spelling/grammar fixes wherever applicable.
An attempt at closing #940 
* Bug fix: No
* New feature: No
=> Typo fixes & Standardize doc string convention

glances/plugins/glances_processlist.py
We split the cmdline of the processes based on the bare process name. Maybe be there is better way of doing this, not sure about it.
This is probably better then adding in a `cmdline[0].startswith("sshd:")` in `split_cmdline` tho 😅 
* Bug fix: yes
* Closes: #1795
=> fix: Command trimmed incorrectly #1795

glances/autodiscover.py
Bug fix for autodiscovery failure
* Bug fix: yes
* Closes: #1969
=> fix: autodiscover.py failure

README.rst
Minor typo fix in Readme
* Bug fix: yes(just in docs tho)
=> fix: Typo in docs

README.rst
pkg install py37-glances 
Does not work
pkg install py38-glances
Does.
I've updated the README to reflect this. 
* Bug fix: yes
=> Updated FreeBSD installation instructions

glances/plugins/glances_help.py, glances/plugins/glances_now.py
Simple fix for wrong behavior of `N` key.
Fix #1974
* Bug fix: yes
* Fixed tickets: #1974
=> Fix N key wrong behavior

docs/aoa/header.rst, glances/plugins/glances_ip.py
Let user optionally disable displaying the Public IP Address
* Bug fix: no
Continuation of #2029
=> Optionally disable public ip

Makefile
For any questions concerning installation or use, please open a discussion (https://github.com/nicolargo/glances/discussions), not an issue. 
Allows the deps to be installed with `venv`. 
* Bug fix: **yes**/no
* New feature: yes/**no**
* Fixed tickets: comma-separated list of tickets fixed by the PR, if any **none**
=> add venv to list of .PHONY in Makefile

Makefile
Add new command make help to display the list of available commands
=> chore(Makefile): add command make help

.github/workflows/test.yml, dev-requirements.txt
Pyright is a static type checker developed by Microsoft.
This tool grows up the quality of code 
* Bug fix:no
* New feature:no
=> chore(ci): add pyright

glances/programs.py
Manage process name if user has no name.
* Bug fix: yes
* Fixed tickets: #2195
=> Correct issue if process has no user name.

Makefile, docker-files/ubuntu.Dockerfile
This PR add a Ubuntu Dockerfile for showing GPU info.
* Bug fix: no
=> Add ubuntu Dockerfile with GPU supported

glances/config.py, glances/exports/glances_cassandra.py, glances/exports/glances_mongodb.py, glances/outdated.py, glances/outputs/glances_bottle.py, glances/password.py, glances/secure.py, glances/server.py, glances/snmp.py, glances/standalone.py
- Add update check disable option details in the warning message.
- Fix wrong precedence in command line args for `--disable-check-update`
- Change default value for `check_update` to be consistent with ones provided in `conf/glances.conf`
* Bug fix: yes
* New feature:no
* Fixed tickets: Issues mentioned in #2276 and other problems
=> Add disable option to Update Check warning msg

glances/outputs/glances_bottle.py, glances/standalone.py, unitest-restful.py
Fix the bug with status endpoint
* Bug fix: yes
* Fixed tickets: Fixes #2282
=> Fix webserver status endpoint

glances/plugins/glances_fs.py
Already fixed in 09c66999
A cleaner implementation of the fix..
In this case, I think fixing the cause of the bug is better than adding a cleanup at the end.
@nicolargo 
What do you suggest when looking at PRs from contributers (like #2299), 
Should I request for cleaner changes in cases where their fix works but could think of a better alternative/solution?
Or should I accept the changes and make the fix cleaner later when possible?  
What are your thoughts on this?
=> Plugin fs - cleaner impl to avoid duplicate entries when allow is set

glances/plugins/glances_docker.py
cause - problem on Unraid's docker Engine API response
* Bug fix: yes
* Fixes: #2233
=> fix: docker - Engine API (Unraid) failing on fetching image 

docker-files/alpine.Dockerfile
Also updates python version to match newer release
=> chg: Dockerfile (alpine) - upgrade img ver to 3.18.0

docker-files/alpine.Dockerfile, docker-files/ubuntu.Dockerfile
Fixes the missing `packaging` dependency issues with the newer docker images
* Bug fix: yes
* Fixed tickets: 2392
=> Fix: missing `packaging` dependency with the new Dockerfile

glances/plugins/containers/glances_podman.py, glances/plugins/containers/stats_streamer.py
A temporary fix to reduce CPU usage of the generator hack introduced in f7f4f389
fix #2390
note: tmp fix
Proper sol - https://github.com/containers/podman-py/pull/266
=> Reduce CPU usage of containers plugin (podman)

glances/outputs/static/package-lock.json, glances/outputs/static/package.json
=> Updated WebUI dependencies

glances/plugins/plugin/model.py
More intelligent module name creation in model.py not depending on fixed indexes.
Final commit on previous PR :-)
* Bug fix: no
=> Optimized plugin name creation

docs/cmds.rst, docs/config.rst
Several typos were found and corrected in the project documentation. These changes affect the following files:
- docs/cmds.rst
- docs/config.rst
These corrections improve the readability and accuracy of the documentation, making it more accessible and understandable for users and developers.
* Bug fix: no
=> Fix typos in project documentation

docs/api.rst, docs/cmds.rst, docs/config.rst, docs/docker.rst, docs/glances.rst, docs/index.rst, docs/install.rst, docs/man/glances.1, docs/quickstart.rst, docs/support.rst
Several typos were found and corrected in the project documentation.
Some grammatical and stylistic improvements were made to enhance clarity and coherence.
These changes affect the following files:
- docs/api.rst
- docs/cmds.rst
- docs/config.rst
- docs/docker.rst
- docs/glances.rst
- docs/index.rst
- docs/install.rst
- docs/quickstart.rst
- docs/support.rst
These corrections and improvements significantly enhance the readability and accuracy of the documentation, making it more accessible and comprehensible for both users and developers.
* Bug fix: no
=> Fix typos and make grammatical and stylistic edits in project documentation

glances/plugins/memswap/__init__.py
=> OpenBSD crash on start without a swap file/partition #2719

docker-files/alpine.Dockerfile
=> chg: docker-files - add build dep for alpine - cmake

AUTHORS, MANIFEST.in, setup.py
followup #2760 
sorry for missing for manifest.in config, also include SECURITY.md
```
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```
* Bug fix: yes
=> fix: include requirements.txt and SECURITY.md for pypi dist

glances/plugins/sensors/__init__.py
=> refactor: plugin(sensors) - cleanup + typing + fixes

requirements.txt
=> chg: requirements.txt - use pydantic v2

glances/event.py, glances/events_list.py, optional-requirements.txt, requirements.txt
=> chg: event_list - enable data validation only if pydantic available

glances/plugins/sensors/__init__.py
=> fix: plugin(sensors) - serialization bug with raw stats

glances/plugins/processlist/__init__.py
=> fix: plugin (processlist) - failure on programs view

glances/plugins/containers/engines/docker.py, glances/plugins/containers/engines/podman.py, glances/plugins/containers/stats_streamer.py
=> fix: containers (podman) - missing support for rootless mode

README.rst
I was reading the README file and noticed that a line was repeated twice. Why not fix it? 🙂
I haven't found related issues regarding this.
* Bug fix: yes
=> Remove duplicate line from the README file

glances/cpu_percent.py, glances/plugins/percpu/__init__.py
=> fix: cpu_percent - initialization timer bugs

docs/docker.rst
Corrected path in the docs for the docker run installation method.
* Bug fix: no
=> Corrected path in docs for docker

glances/plugins/system/__init__.py
Part of #2801. Local tests are all passing:
```shell
Ran 37 tests in 13.245s
OK
```
Broke `update` in two parts:
* if `local`, stats taken from `get_stats_from_std_sys_lib`
* and readability achieved by `add_human_readable_name`
* else if `snmp`, taken from `update_stats_with_snmp`.
`get_stats_from_std_sys_lib` has two helpers:
1. `get_win_version_and_platform`.
2. `get_linux_version_and_distro`.
=> Reduced complexity of `glances.plugins.system.PluginModel.update()`

glances/plugins/percpu/__init__.py
Part of #2801. Quick look:
No quick look:
Tests are all passing:
```shell
Ran 37 tests in 13.136s
OK
```
Broken `msg_curse`: if no stats returns empty list, else:
1. `define_headers_from_os`
2. `maybe_build_string_msg`
3. `display_cpu_stats_per_line`
4. `manage_max_cpu_to_display`
5. Then, for CPU:
* `display_cpu_header_in_columns`
* `display_cpu_stats_in_columns`
6. Hence, `summarize_all_cpus_not_displayed`
=> Reduced complexity of `glances.plugins.percpu.PluginModel.msg_curse()`

unittest-core.py
Part of #2801. All tests are passing:
```shell
Ran 37 tests in 13.053s
OK
```
Common tests follows the flow:
* `reset_stats_history_and_views`
* `do_checks_before_update`
* add first element with `update_stats`
* `check_stats`
* `filter_stats`
* add second element `update_stats`
* `chk_hist_maybe_add_third_elem`
* `check_views`.
=> Reduced complexity of `unittest-core.TestGlances._common_plugin_tests()`

glances/outputs/glances_colors.py
=> chg: curses - change colors for some LOG styles

Makefile, docs/api.rst
Part of #2906.
Factorized rules with variables.
=> Refactorize `Makefile`

glances/plugins/raid/__init__.py
=> fix: plugin (raid) - Show degradation only when stats are available

glances/outputs/glances_curses.py
Part of #2801. All tests are passing:
```shell
Ran 37 tests in 12.936s
OK
```
Broken down `__catch_key` in two parts:
* `catch_actions_from_hotkey`
* `catch_other_actions_maybe_return_to_browser`.
=> Reduced complexity of `_GlancesCurses.__catch_key()`

Makefile
Part of #2906.
* used patterns in rules targetting `test-*`, `docker-*`, `run-docker-*`
* `make help` is unchanged.
=> Refactorized `Makefile` by using pattern rules

glances/plugins/processlist/__init__.py
Part of #2801. User experience is unchanged: on top, after the change; below, before the change.
`ret` goes through these steps:
* `add_title_line`
* `add_cpu_line`
* `maybe_add_cpu_affinity_line`
* `maybe_add_ionice_line`
* `add_memory_line`
* `add_io_and_network_lines`
* `append_newlines`
=> Reduced complexity of `PluginModel.__msg_curse_extended_process_thread()`

glances/plugins/containers/__init__.py
- part of #2801: this one might be cumbersome to review, I changed a lot of lines
- tests are all passing; user experience is the same (see screenshot: top, after changes; down, version 4.1.2)
- I don't have containers in local; it would be helpful to test with a machine that has containers.
Broken down in:
* `build_tile`
* `build_header`
* on each container, `build_data_line` calls `build_container_data`.
`build_container_data` does for a container:
* `maybe_add_engine_name_or_pod_name`
* `build_container_name`
* `build_status_name`
* `build_uptime_line`
* `build_cpu_line`
* `build_memory_line`
* `build_io_line`
* `build_net_line`
* `build_cmd_line`.
=> Refactorized `glances.plugins.containers.PluginModel.msg_curse()`

glances/plugins/containers/engines/__init__.py, glances/plugins/vms/engines/__init__.py
=> fix: typing - compatibility with py3.8

Makefile
Part of #2906.
* `profiling-*` share the same start banner
* used `OUT_DIR` for static outputs
* `TIMES` controls the number of iterations.
=> Refactorized rules targetting `profiling-*` & `memory-profiling`

glances/exports/glances_graph/__init__.py, glances/exports/glances_json/__init__.py, glances/exports/glances_kafka/__init__.py, glances/exports/glances_zeromq/__init__.py, glances/globals.py, glances/outputs/glances_restful_api.py, glances/plugins/ip/__init__.py
=> JSON serialization fallbacks on ujson and builtin json lib

glances/outputs/glances_curses.py
Part of #2801. Tests are passing:
```shell
Ran 37 tests in 13.730s
OK
```
After:
Before:
The flow is unchanged. Used as helpers:
1. `self.set_upper_left_pos`
2. `self.goto_next_and_ret_first_col`
3. `self.check_opt_and_add`
4. `self.x_overbound`
5. `self.y_overbound`
6. `self.display_msg`
=> Refactorized `_GlancesCurses.display_plugin()`

glances/plugins/alert/__init__.py
All tests are passing:
```shell
OK
```
After:
Before:
* closes #2416
* `msg_curse` calls `loop_over_alert`
* `loop_over_alert` loops each alert with:
1. `add_new_line`
2. `add_start_time`
3. `add_duration`
4. `add_infos`
5. `add_min_mean_max`
6. `add_top_proc`
=> Refactorized alert plugin

glances/plugins/diskio/__init__.py, glances/plugins/folders/__init__.py, glances/plugins/fs/__init__.py, glances/plugins/irq/__init__.py, glances/plugins/network/__init__.py, glances/plugins/ports/__init__.py, glances/plugins/sensors/__init__.py, glances/plugins/smart/__init__.py, glances/plugins/wifi/__init__.py
Fixed typos, refactored  [`glances.plugins.ports.PluginModel.msg_curse()`](https://scrutinizer-ci.com/g/nicolargo/glances/code-structure/develop/py-function/glances.plugins.ports.PluginModel.msg_curse)
Part of #2801.
=> Fixed typos, refactored  `glances.plugins.ports.PluginModel.msg_curse()`

glances/globals.py
* refactored [`glances.globals.pretty_date()`](https://scrutinizer-ci.com/g/nicolargo/glances/code-structure/develop/py-function/glances.globals.pretty_date)
* part of #2801
* all tests are passing
```shell
OK
OK
OK
```
After:
Before:
* instead of many, a single return point is used
* refactoring possible because [`OrderedDict` preserve insertion order](https://docs.python.org/3/library/collections.html#collections.OrderedDict)
* though [`dict` preverse order since 3.6](https://peps.python.org/pep-0520/), used `OrderedDict` for safety
* introduced as helpers:
1. `get_diff_time`
2. `get_msg_for_true_cond`
3. `get_conds_for_sec_diff_msg`
4. `get_conds_for_day_diff_msg`.
=> Refactored `glances.globals.pretty_date()`

glances/exports/glances_mqtt/__init__.py
Added the forgotten topic retain, but important for this kind of data
* Bug fix: yes
=> Add retain to availability topic

glances/globals.py
Reverts nicolargo/glances#2961 because it introduce a bug: https://github.com/nicolargo/glances/issues/2973
=> Revert "Refactored `glances.globals.pretty_date()`"

conf/glances.conf, docker-compose/glances.conf, glances/plugins/diskio/__init__.py, glances/plugins/plugin/model.py
This PR is adding new options to the config file 
```
[diskio]
hide_threshold_bytes=0
```
and 
```
[network]
hide_threshold_bytes=0
```
And then performing a comparison in `glances/plugins/plugin/model.py` to see if a value should be hidden or not.
* Bug fix: no
* Fixed tickets: #2958
=> Implement Improve hide_zero option #2958

glances/globals.py
* refactored `glances.globals.pretty_date()`, version 2
* all tests are passing:
```shell
OK
OK
OK
```
* part of #2801
* follows from f6279baacd4cf0b27ca10df6dc01f091ea86a40a; which caused #2973.
=> Refactored `glances.globals.pretty_date()`, version 2

docker-files/alpine.Dockerfile, docker-files/ubuntu.Dockerfile, glances/__init__.py, pyproject.toml
Fixes #2956, use a dynamic version so the app doesn't need to be installed 
- Bug fix: yes
- New feature: no
- Fixed tickets: comma-separated list of tickets fixed by the PR, if any
=> Make pyproject.toml's version dynamic

glances/processes.py
=> Refactored `glances.processes.GlancesProcesses.update`

glances/processes.py
Reverts nicolargo/glances#3009 because it make Glances CPU consumption > 100%
=> Revert "Refactored `glances.processes.GlancesProcesses.update`"

docs/conf.py, glances/processes.py
After: 
Before:
* part of #2801
* second take of 1fda541350aad89337cfabf94f263640a15edc4c
* reverted in 0c635af10dbb77756ef91a1ae5a58634fab4d3bf.
=> Refactored `glances.processes.GlancesProcesses.update`, version 2

README.rst
Updates 4/6/2025: FreeBSD Section for Glances
=> Updates 4/6/2025: FreeBSD Section - Glances - An Eye on your System

glances/plugins/mem/__init__.py
Part of #2801.
```
venv/bin/python -m pytest tests/test_core.py
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.10.12, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/ariel/src/glances
configfile: pyproject.toml
plugins: anyio-4.9.0
collected 37 items                                                                                                                                                                          
tests/test_core.py .....................................                                                                                                                              [100%] …
```
=> plugins: mem: reduce code complexity

glances/plugins/connections/__init__.py
Extracted `update_with_net_connections_method` and `update_with_nf_conntrack_method` from `update`.
After:
Before:
Part-of #2801, refactor of [`update`](https://scrutinizer-ci.com/g/nicolargo/glances/code-structure/develop/py-function/glances.plugins.connections.PluginModel.update)
=> plugins: connections: refactor

glances/plugins/connections/__init__.py
Extracted `update_with_net_connections_method` and `update_with_nf_conntrack_method` from `update`.
Second take of #3161.
After:
Before:
Part-of #2801, refactor of [`update`](https://scrutinizer-ci.com/g/nicolargo/glances/code-structure/develop/py-function/glances.plugins.connections.PluginModel.update)
=> plugins: connections: refactor, version 2

glances/outputs/static/js/components/plugin-containers.vue, glances/outputs/static/webpack.config.js
=> Update plugin containers display and order #3186
