nicolargo/glances

- glances/outputs/static/html/plugins/processlist.html
- glances/outputs/static/js/stats_controller.js
If io_counters is not available in the process list, the Web UI crash.
I tried to reproduce the functioning of https://github.com/nicolargo/glances/blob/develop/glances/plugins/glances_processlist.py#L259
> [Web UI] Fix process list when no I/O

- glances/outputs/static/html/plugins/cpu_more.html
- glances/outputs/static/html/plugins/mem_more.html
See #560 : irq, iowait, steal, buffers and cached shouldn't be displayed on OS X
> [Web UI] Hide values when not available

- glances/outputs/static/css/style.css
The web UI now uses magenta for WARNING (same as curse).
> [Web UI] Fix color of WARNING

- docs/glances-doc.rst
- glances/exports/glances_influxdb.py
This adds support for the JSON payload schema used in 0.9.x. This
also adds support for the tags feature available in 0.9.x via the
config option tags. Tags is a comma separated list of colon
separated key:value pairs. An example:
```
[influxdb]
tags = foo:bar,spam:eggs,region:us-east-1
```
> Support InfluxDB 0.9.x

- unitest-restful.py
- unitest-xmlrpc.py
This changes allows the user to run the unittests properly in
a virtualenv setup. Once the venv activated, /usr/bin/env
will point the python executable within the venv instead of
the system one.
> unittest: start server in a modified environment.

- glances/plugins/glances_sensors.py
This fix translates the characters to an appropriate encoding for the
terminal. "Â°C" (A acute, degrees, C) was being output on latin1
terminals, which is a bug since the LC_CTYPE locale setting should tell
the program whether it's okay to output Unicode.
This follows the recommendation from the official curses library
documentation: https://docs.python.org/2/library/curses.html
Steps to reproduce the issue:
1. Install pysensors, enable any kernel modules necessary to support it
2. Run `LANG=en_US rxvt -e glances`
3. Look in SENSORS section
The corrupt Unicode character sequence will appear.
> Fix UTF-8 characters being output on latin1 terminals

- glances/outputs/glances_bottle.py
* read debug file in the temp dir 
* do not raise an error if debug file does not exist
* rename **debug.json** into **glances-debug.json** in order to avoid name conflict
Fix #650.
> [Web UI] Fix debug mode

- glances/outputs/static/html/plugins/processlist.html
Since the refactoring of the webUI, the IO Write is missing in the process list.
Before : 
After :
> [WebUI] fix io write in the process list

- glances/outputs/static/html/help.html
Since the PR #664 we use 24 columns layout but the help page was still on 12 columns.
Before : 
After :
> [WebUI] Fix layout of the help page

- glances/outputs/static/html/plugins/per_cpu.html
- glances/plugins/glances_percpu.py
Since the commit 1945db14fce4259758bc1a34c2aaf4de90f6a204, I have the following error with per cpu : 
```
File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/Users/f.brutel/dev/octey/dev/glances/glances/__main__.py", line 38, in <module>
glances.main()
Per CPU : test if stat exists for the cpu
File "glances/__init__.py", line 125, in main
standalone.serve_forever()
File "glances/core/glances_standalone.py", line 108, in serve_forever
return self.__serve_forever()
File …
```
> Fix percpu when stats are missing

- glances/plugins/glances_docker.py
```
File "/usr/bin/glances", line 9, in <module>
load_entry_point('Glances==2.3', 'console_scripts', 'glances')()
File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 119, in main
args=core.get_args())
File "/usr/lib/python2.7/site-packages/glances/core/glances_standalone.py", line 62, in __init__
self.stats.update()
File "/usr/lib/python2.7/site-packages/glances/core/glances_stats.py", line 156, in update
self._plugins[p].update()
File "/usr/lib/python2.7/site-packages/glances/plugins/glances_plugin.py", line 633, in wrapper
ret = fct(*args, **kw)
File "/usr/lib/python2.7/site-packages/glances/plugins/glances_docker.py", line 154, in update
for c in self.stats['containers']:
TypeError: 'NoneType' object is not iterable
```
> tback: docker.containers() can return None

- glances/outputs/static/js/filters.js
When value < 1024, the helper displayed the full value. Now the helper show the value without precision.
Before : 
After :
> [WebUI] Fix auto unit helper

- glances/outputs/static/js/services/plugins/glances_processcount.js
Set default values of processcount plugin to 0.
before : 
after :
> [WebUI] fix process count for stopped

- docs/glances-doc.rst
- glances/main.py
- glances/outputs/glances_curses.py
- man/glances.1
This replaces PR #735, which was:
> I've just found Glances, and i really like it, but i've had the same issue described in #68 — the ANSI background colours (especially green) clash with my terminal colour scheme, making the CPU percentages unreadable.
> This PR adds an option `--disable-bg` which turns off the ANSI background colours: white-on-green becomes standard green, white-on-magenta becomes standard magenta, &c.
> I modelled the new option after the `--disable-bold` one, whose variable seems to be stored backwards from what i'd expect (`args.disable_bold == True` actually means bold is *not* disabled). I don't get why it's like that, but i copied the same behaviour for the new option.
> Add option to disable ANSI background colours (2)

- docs/glances-doc.rst
An argument is mandatory for the `code-block` directives.
> Fix warning on code-block directives

- glances/outputs/static/js/stats_controller.js
With this fix, the WebUI makes the first loading of data then refresh the data every x seconds.
> [WebUI] Dont wait before first loading

- glances/client_browser.py
**New pull request to address fix in develop**
I was trying to run glances in browser mode and got below `IndexError`. This happens only when there is no server available. On probing further I found that the problem was comparison of active_server with `NoneType` with `is`. In failure case `active_server` is 0, hence the condition failed. I grep'd through the code and found that `active_server` holds the current cursor position and its an integer. Hope this fix helps. BTW, awesome project. I am still learning new stuff from glances!
```
(env)rkadam@rkadam-vbox:~/github/glances$ glances --browser
File "/home/rkadam/github/glances/env/bin/glances", line 9, in <module>
load_entry_point('Glances==2.5.1', 'console_scripts', 'glances')()
File …
```
> IndexError in browser mode

- glances/plugins/glances_docker.py
File "/home/grw/src/glances/venv/bin/glances", line 11, in <module>
sys.exit(main())
File "/home/grw/src/glances/venv/lib/python3.4/site-packages/glances/__init__.py", line 125, in main
standalone.serve_forever()
File "/home/grw/src/glances/venv/lib/python3.4/site-packages/glances/core/glances_standalone.py", line 108, in serve_forever
return self.__serve_forever()
File "/home/grw/src/glances/venv/lib/python3.4/site-packages/glances/core/glances_standalone.py", line 89, in __serve_forever
self.stats.update()
File "/home/grw/src/glances/venv/lib/python3.4/site-packages/glances/core/glances_stats.py", line 156, in update
self._plugins[p].update()
File "/home/grw/src/glances/venv/lib/python3.4/site-packages/glances/plugins/glances_plugin.py", line 654, in …
> fix crash in docker plugin if cpu usage not available

- README.rst
Using HTTP will cause a CONNECTION_RESET error:
```
curl -L http://bit.ly/glances | /bin/bash
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
```
> Change http://bit.ly to https://bit.ly

- glances/outputs/static/html/plugins/fs.html
Before : 
After :
The device name is now displayed only on large screen. Long device names are no longer displayed at all. 
Fix #731.
> [Web UI] Fix display issue in fs plugin with long device name

- README.rst
- docs/cmds.rst
- docs/gw/riemann.rst
- docs/man/glances.1
- glances/exports/glances_riemann.py
- glances/main.py
This patch introduces a new export method for sending metrics to
__Riemann__ server using _TCP_ protocol. The module can be enabled like
all the other exports in __Glances__, specifying the `--export-riemann`
option.
Sending metrics to Riemann requires
[bernhard](https://github.com/banjiewen/bernhard) that is
the most popular _Riemann client_ written in python.
In the configuration file you can only specify the `host` and `port`
that riemann is listening for new connections on. Later new options are
planned to be added like __SSL__ support and __UDP__.
Documentation and manpages are refreshed according to the modifications
in the config options and introducing the usage of Riemann export.
Signed-off-by: Gergő Nagy <grigori.grant@gmail.com>
> exports: riemann export implemented and documented

- glances/outputs/static/html/plugins/cpu.html
- glances/outputs/static/js/services/plugins/glances_cpu.js
Hide *ctx_switches*, *interrupts*, *soft_interrupts* and *syscalls* in the WebUI if the data are not available.
* Bug fix: yes
* Fixed tickets: -
Before : 
After :
> [WebUI] Hide additional cpu data if not available

- conf/glances-grafana.json
This modifies the sda2 disk IO section to account for the (default) 3 second gap.
* Bug fix: yes
* Fixed tickets: none, but relates to #856
> Correct Grafana dashboard - disk I/O

- .github/ISSUE_TEMPLATE.md
- NEWS
- README.rst
- glances/exports/glances_elasticsearch.py
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- README.rst
There's no quick reference available on how to run the docker container in web server mode. Also the GLANCES_OPT used in the Dockerfiles is powerful but you'll have to check the Dockerfile to know it's there.
* Bug fix: no
> add docker container web server mode example in readme

- glances/plugins/glances_docker.py
Crashes when using glances docker plugin.
Cause: logging with an unbound local variable 'e'
* Bug fix: yes
> missing local variable "e"

- glances/plugins/glances_cpu.py
On an a particular OpenVZ container the soft_interrupts is None and causes a TypeError due to no type check before ```getattr(cpu_stats, stat) - getattr(self.cpu_stats_old, stat)```
* Bug fix: yes
* Glances: v2.7.1 & v2.8_DEVELOP
* PSutil: v4.4.2
* Operating System: Ubuntu 12.04.5 LTS
```
cpustats(ctx_switches=23729700634, interrupts=0, soft_interrupts=None, syscalls=0)
File "/usr/local/lib/python2.7/dist-packages/Glances-2.8_DEVELOP-py2.7.egg/glances/plugins/glances_cpu.py", line 139, in update_local
self.stats[stat] = getattr(cpu_stats, stat) - getattr(self.cpu_stats_old, stat)
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
> Fix cpu_stats TypeError

- glances/plugins/glances_gpu.py
Single line fix to correctly register the gpu plugin key for each device id.  This is a continuation of #170 and #979.
This PR is now tested.  For instance, here is the API output for an **old** card (which does not support the processor utilization query in the Nvidia management library:
1.  No load
```
$ curl http://localhost:61208/api/2/gpu
[{"memory_percent": 0, "processor_percent": null, "gpu_id": 0, "name": "GeForce GTX 560 Ti"}]
```
2. Training a 128 node, single hidden layer recurrent neural net
```
$ curl http://localhost:61208/api/2/gpu
[{"memory_percent": 14, "processor_percent": null, "gpu_id": 0, "name": "GeForce GTX 560 Ti"}]
```
3. Training a 1024 node-per-layer, 3 hidden layer recurrent neural net
```
$ curl http://localhost:61208/api/2/gpu
[{"memory_percent": 98, …
```
> Fix incorrectly registered GPU id in gpu plugin

- glances/plugins/glances_gpu.py
A small typo prevented GPU stats reporting in the glances interface.  This fixes it.  The curses interface now looks like this:
Notice the `GPU GRID K520` area.  😄 
* Bug fix: yes
* Fixed tickets: 170
> Feature/gpu nvidia - curses interface bugfix

- docs/aoa/network.rst
form -> from
Fix typo in network text. It was writen "form" when I think you meant "from".
* Bug fix: no
* Fixed tickets: None
> Fix typo in network text

- glances/stats.py
From a fresh pip install I was getting the following error. Removing the extra } fixed the issue and allowed glances to run.
```python
File "/bin/glances", line 11, in <module>
load_entry_point('Glances==2.9.0', 'console_scripts', 'glances')()
File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 134, in main
start(config=config, args=args)
File "/usr/lib/python2.7/site-packages/glances/__init__.py", line 100, in start
mode = GlancesMode(config=config, args=args)
File "/usr/lib/python2.7/site-packages/glances/standalone.py", line 43, in __init__
self.stats = GlancesStats(config=config, args=args)
File "/usr/lib/python2.7/site-packages/glances/stats.py", line 47, in __init__
self.load_modules(self.args)
File …
```
> Remove extra } in format string

- glances/main.py
- glances/outputs/glances_bottle.py
With this PR, glances will be able to read password from ``<any_user>.pwd`` file. Currently it only works for ``glances.pwd``.
This also changes the realm displayed during authentication from ``private`` to ``glances`` as default.
Sample usage:
``glances -w --password --username-default=<any_user> --realm=<any_realm>``
* Bug fix: yes
> add option to change default username and realm

- glances/compat.py
In python2, binary type is native string type, so function b and nativestr should be the same. In python3, unicode is native string and binary is encoded unicode type. Now the question comes, why do we encode unicode string in python3 by encode('latin-1') instead using utf-8?
Note: I fixed the bug for ZeroMQ by modifying the compat file, still needs further test system wide to make sure the type checking and translating is totally correct.
The original code is causing "Frame does not support the buffer interface" error in ZeroMQ @ https://github.com/zeromq/pyzmq/blob/master/zmq/sugar/socket.py line 373 in socket.recv_multipart. I looked up the code and find out the function b() in glances.compat is actually returning the unicode object. So it's basically a bug of unicode does not support …
> Python encoding in python2 and python3

- glances/outputs/static/js/filters.js
- glances/outputs/static/public/js/main.min.js
problem: min_size outputs names longer than max
old: min_size('some_name', 8) -> "_ome_name"
solution: add 1 to substring offset
new: min_size('some_name', 8) -> "_me_name"
* Bug fix: yes
> fix min_size to not output string with more than max characters

- NEWS
- docs/gw/index.rst
- docs/gw/json.rst
- glances/exports/glances_json.py
- glances/main.py
The goal of this PR is to export stats in JSON so that it can be ingested and processed by external downstream systems like Kafka and Kinesis. Following is an example of a JSON stats object and each such object would be outputted on every new line in the file:
```
{"load": {"min15": 2.3232421875, "min5": 2.3349609375, "cpucore": 8, "load_warning": 1.0, "min1": 2.298828125, "history_size": 28800, "load_critical": 5.0, "load_careful": 0.7}, "docker": {}, "uptime": {"seconds": 1461911, "history_size": 28800}, "fs": {"/.device_name": "/dev/disk1", "/.fs_critical": 90.0, "/.mnt_point": "/", "/.free": 81012445184, "/.size": 499082485760, "/.fs_careful": 50.0, "/.used": 417807896576, "/.fs_type": "hfs", "/.key": "mnt_point", "/.fs_warning": 70.0, "/.history_size": 28800, "/.percent": 83.8}, …
```
> Export json

- glances/plugins/glances_hddtemp.py
~~It looks like hddtemp is a very non-deterministic piece of software and
does not grant that every connection will receive data for all devices
that were in the previous one, thus making a device and its temperature
disappear and reappear in the list once in a while.~~
Since the first implementation of the hddtemp plugin, Glances wasn't retrieving
all data from the hddtemp server, making the device disappear and reappear
in the list once in a while.
* Bug fix: yes
>  Prevent data truncation when receiving data from hddtemp server

- docs/aoa/load.rst
Fixes a typo that prevented 'load on BSD' from rendering properly as a link.
In the documentation, 'load on BSD' should render as a link but doesn't, due to a spurious `S` at the start - presumably a typo.
* Bug fix: yes
> Fixes a link rendering problem in load.rst

- snap/snapcraft.yaml
Fix the snap, which was missing the mount-observe and system-observe interfaces.
```
snapcraft
sudo snap install *.snap
sudo snap connect glances:system-observe
sudo snap connect glances:mount-observe
```
Once we have a revision with this change pushed to the store, I'll volunteer to request auto-connection for those two interfaces so end users just have to type `sudo snap install glances`.
* Bug fix: yes
> Add missing mount-observe and system-observe interfaces

- glances/plugins/glances_ip.py
glances shouldn't hit the network if there's no need to. This is especially annoying for me because I monitor outgoing network traffic and get an alert every time I run glances, even with `--disable-ip`.
* Bug fix: yes
> Don't load public IP address if module disabled

- README.rst
glances itself is [now](https://github.com/Homebrew/homebrew-core/pull/22538) packaged by Homebrew.
> Update Homebrew installation instructions

- README.rst
slightly better way which:
- doesn't leave the container around when finished
- uses network host mode which then allows glances to show the network devices
improve docker run command in readme
> update readme docker run command

- glances/plugins/glances_diskio.py
Sorts Disk I/O by aliases (if present) or device names and treats numbers as numbers.
Prevents situations such as `sda10` being above `sda2` or `alias` between `sda1` and `sda3`.
* Bug fix: no
> Implement number and alias aware diskio sorting

- glances/processes.py
Fix TypeError encountered under macOS and python v3 (works correctly with python v2)
> TypeError: '>' not supported between instances of 'NoneType' and 'float'
* Bug fix: yes
> fix on macOS when value is NoneType when compute the max values

- glances/standalone.py
Before this patch, running `glances -q -t 10` resulted in 100% utilization. After this patch, glances properly wakes up only once every 10 seconds to collect data. This is usable when periodically exporting data to an external service.
* Bug fix: yes
* Fixed tickets: Maybe #1262
> Don't use 100% CPU in quiet mode

- docs/man/glances.1
During Debian packaging, `lintian` throw a warning about this typo, here is a little PR in order to fix that :-)
* Bug fix: yes
* Fixed tickets: -
> docs: manpage - Fix spelling typo

- setup.py
As the web interface is needed on Windows (as there is no Curses interface), make sure all of the web requirements are included on Windows. This includes `bottle` (already listed) and `requests` (now added).
* Bug fix: yes
* Fixed tickets: https://github.com/nicolargo/glances/issues/1167
> Require `requests` on Windows

- README.rst
- docs/docker.rst
improve documentation of glances with docker.
My Docker version 18.09.0, build 4d60db4
if I run this 
```bash
docker run -v ./glances.conf:/glances/conf/glances.conf -v /var/run/docker.sock:/var/run/docker.sock:ro --pid host -it docker.io/nicolargo/glances
``` 
I have this error `docker: Error response from daemon: create ./glances.conf: "./glances.conf" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.`
So in agreement with docker document https://docs.docker.com/storage/bind-mounts/, we can replace ./ by \`pwd\`
\`pwd\`.conf instead of ./glances.conf for docker run command in documentation
* Bug fix: yes
* Fixed …
> `pwd`.conf instead of ./glances.conf for docker run command

- .gitignore
- glances/client_browser.py
- glances/outputs/glances_curses_browser.py
- glances/plugins/glances_ports.py
- glances/web_list.py
Client Browser's thread management added.
Curses Browser's key bug fixed.
1.  Glances browser created too many thread and used too much memories.  
For example, I added 200 servers, Glances browser created 5000+ threads and used 200+MB memories. 
2. PageDown key minor bug fixed. 
PageDown key didn't work at end of page.
3. port plugin ssl verify and proxy option added. 
- ssl verify : defualt True, optional False and /path/to/certi.cer 
ex)  web_1_ssl_verify=False
web1_ssl_verify="/Users/foo/mycert.cer" 
- http/https proxy added: default None
ex) web_1_http_proxy = "192.168.0.1:8080"
web_2_https_proxy="192.168.0.1:8080"
* Bug fix: yes
> Client Browser's thread management added.

- README.rst
The docker plugin sure seems to work on macOS, not just Linux. I tested it locally on macOS 10.13.6. Should the README be updated to note that it works there too?
* Bug fix: no
> README: note that docker plugin works on Mac

- conf/glances.conf
- glances/exports/glances_cassandra.py
The goal of the PR is to add the possibility to export throw a Cassandra with authenticator (username/password) 
I follow this https://datastax.github.io/python-driver/api/cassandra/auth.html
* Bug fix: no
> add authprovider for cassandra export

- .gitignore
- glances/outputs/glances_curses_browser.py
* Curses's browser server list sorting added.
using key '1', '2' , '3'.
key '1' is normal. (don't use sorting)
key '2' is using sorting with ascending order. 
ONLINE > SNMP > PROTECTED > OFFLINE  > UNKNOWN
key '3' is using sorting with descending order.
*  Curses's browser server status count added. 
> Curses's browser server list sorting added. 

- snap/snapcraft.yaml
Closes #1403
Allow use of configuration files when installed as snap.
Valid configuration files are:
* `/etc/glances/glances.conf`
* `~/*`
* Bug fix: yes
* Fixed tickets: 1403
> Allow use of configuration files when installed as snap.

- glances/exports/glances_elasticsearch.py
makes indices date-based (e.g. `glances-2019.03.13`) and also makes all fields of type `keyword`.  That is a hack and I will probably try to fix it later.
* Bug fix: yes
* Fixed tickets: comma-separated list of tickets fixed by the PR, if any #1272
> add date to index, unbreak object push

- conf/glances.conf
This hides about a dozen loop back file systems on my Ubuntu 18.04 machine, cleaning up the side bar tremendously.
* Bug fix: Some loop back file systems do not get ignored, cluttering the side bar.
> Ignore loop back file systems under Ubuntu

- snap/snapcraft.yaml
This patch fixes the following error: 
```
$ glances --web-server
Glances Web User Interface started on http://0.0.0.0:61208/
File "/snap/glances/x1/bin/glances", line 11, in <module>
nces')()
File "/snap/glances/x1/lib/python3.5/site-packages/glances/__init__.py", line 140, in main
start(config=config, args=args)
File "/snap/glances/x1/lib/python3.5/site-packages/glances/__init__.py", line 109, in start
mode.serve_forever()
File "/snap/glances/x1/lib/python3.5/site-packages/glances/webserver.py", line 48, in serve_forever
self.web.start(self.stats)
File "/snap/glances/x1/lib/python3.5/site-packages/glances/outputs/glances_bottle.py", line 218, in start
quiet=not self.args.debug)
File "/snap/glances/x1/bin/bottle.py", line 755, in run
run(self, **kwargs) …
```
> snap: Fix broken --webserver due to missing network-bind plug

- .gitignore
Avoid showing snap build artifacts as untracked files, this should also make the -dirty tag in the snap version string disappear.
* Bug fix: kinda
> snap: Add packaging-specific gitignore rules

- glances/plugins/glances_sensors.py
sensor aliases currently work in the curses interface, but not in the
web one
fixes #1456
> show sensors alias in web interface

- glances/plugins/glances_ip.py
I just noticed that httpbin.org is returning duplicate IP addresses in the format "1.2.3.4, 1.2.3.4". Here is a cosmetic fix that deduplicates the data. 
* Bug fix: yes
* Fixed tickets: None
> Filter duplicate public IP addresses in IP plugin

- docker-files/devel-arm/Dockerfile
`future` has been added to requirements.txt, but is missing from arm Dockerfile.
Instead of adding future directly, I install all requirements so this should not be a problem in the future. Another improvement could be to install optional-requirements.txt so all modules are made available in the base image.
* Bug fix: yes
* Fixed tickets: n/a
> Fix missing future in devel-arm Dockerfile

- glances/exports/glances_influxdb.py
Fix typo on protocol configuration, as protocol is empty `ssl=(self.protocol.lower() == 'https'),` fails, therefore an error is thrown on startup when InfluxDB is configured.
* Bug fix: yes
* Fixed tickets: #1514
> :ambulance: Fix typo for protocol, fixes #1514

- glances/main.py
- glances/outputs/glances_bottle.py
The cmd `glances -t 30 -w` was not working because in web UI mode, the time arg was force to 5 seconds.
* Bug fix: yes
* Fixed tickets: #1521
> Fix custom refresh time in the web UI

- glances/outputs/glances_sparklines.py
Pretty straight-forward, e was not defined causing glances to crash when encoding is not UTF-8
With this fix, a warning is appended to the log. Reproduced below:
```
2019-11-14 05:27:38,350 -- WARNING -- UTF-8 is mandatory for sparklines ('ascii' codec can't encode characters in position 0-39: ordinal not in range(128))
```
* Bug fix: yes
* Fixed tickets: (none)
> Bug fix for UTF-8 check

- glances/plugins/glances_processlist.py
Fix method calls on `config` triggering an `AttributeError` when no config files were found
* Bug fix: yes
* Fixed tickets: #1569
> Fix broken method call when config is None

- docker-files/master/Dockerfile
As described in issue #1662 and [glancesautoinstall#39](https://github.com/nicolargo/glancesautoinstall/issues/39), I have tried to use glances in docker. Unfortunately the image was not up to date. I tried to build it in local but your Dockerfile was not working with last ubuntu 20.04 because package python-pip got removed from officiel repo.
I have decided to rewrite your dockerfile explicity was should be install to get it work on ubuntu:20.04. I fixed the FROM image to avoid the same kind of issue later.
I hope it helps.
Thank you
* Bug fix: yes
* Fixed tickets: #1662, [glancesautoinstall#39]
> Update master dockerfile for Ubuntu 20.04

- docs/aoa/fs.rst
This should fix some formatting issues on the FileSystem documentation page:
* Bug fix: yes
* New feature:no
* Fixed tickets: /
> Fixed formatting on FS example

- docs/aoa/actions.rst
- docs/aoa/fs.rst
- glances/plugins/glances_fs.py
`psutill` [says the following](https://github.com/giampaolo/psutil/blob/master/psutil/_psposix.py):
>  Note: UNIX usually reserves 5% disk space which is not accessible
by user. In this function "total" and "used" values reflect the
total and used disk space whereas "free" and "percent" represent
the "free" and "used percent" user disk space.
This commit fixed the alert value that has been notified in this issue https://github.com/nicolargo/glances/issues/1658.
The issue https://github.com/nicolargo/glances/issues/644 has fixed it one way, this PR is completing the fix for the alert feature of the `fs` plugin.
* Bug fix: yes
* Fixed tickets: https://github.com/nicolargo/glances/issues/644, https://github.com/nicolargo/glances/issues/1658
> Reflect "used percent" user disk space for [fs] alert

- docs/aoa/sensors.rst
Fix grammar:
Glances can display**s** the sensors information using ``psutil`` and/or
Glances can display the sensors information using ``psutil`` and/or
* Bug fix: yes
> Fix grammar in sensors documentation

- glances/outputs/static/js/components/plugin-docker/controller.js
- glances/outputs/static/js/components/plugin-docker/view.html
- glances/plugins/glances_docker.py
Add `rss` and `cache` memory stats for containers.
Docker plugin now returns `rss` and `cache` stats for containers. These were commented out due to them not being present in Docker 1.11 (maybe due to a bug in Docker?) See https://github.com/nicolargo/glances/issues/848. Since these stats are available in newer versions of Docker I thought it'd be nice to bring them back.
I've also added an additional column for `rss` in the web UI for containers.
* Bug fix: no
* Fixed tickets: Enhacement https://github.com/nicolargo/glances/issues/1694
> Add RSS metric for containers

- .github/workflows/main.yml
- README.rst
Add linux/arm/v6 docker platform for RPI0 support.
I tested this on a rpi0w. Only using the api is completely fine. Using the web ui leads to 30-50% CPU load.
* Bug fix: no
> (ci): Add linux/arm/v6 docker platform

- glances/static_list.py
There is a small typo in glances/static_list.py.
Should read `optional` rather than `optionnal`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, optionnal -> optional

- docs/docker.rst
Add clear instructions about enabling password protection when Glances is running inside a Docker container to the ReadTheDocs documentation.
* Bug fix: no
* Fixed tickets: #1674
> Add documentation about password protecting Docker

- docs/docker.rst
Adds clear instructions about enabling password protection when Glances is running inside a Docker container to the ReadTheDocs documentation.
Previous PRs from `patch-1` (#1777 and #1778 ) should be disregarded, this has been rebased on `develop`, whereas they were targeting `master`.
* Bug fix: no
* Fixed tickets: #1674
> Documentation to password protect Dockerized Glances

- glances/config.py
- glances/main.py
- glances/plugins/glances_now.py
Add an option in the .conf and commandline to change the strftime format.
Set `ConfigParser(interpolation=None)` because otherwise you have to write `%%Y%%M` and so on. I don't think interpolation is used anywhere?
Also set the `[global]` config option `check_updates` to false by default. Since `[global]` exists, because `strftime_format` is set under it, **outdated.py** complains about `check_update` not being set otherwise.
Thoughts?
> Add option to set the strftime format

- .github/workflows/build.yml
Fixes the failing docker build.
I forgot the `nicolargo/glances` prefix in my previous MR, so docker tried to push to `dev`.
Which is obviously not allowed.
Now the images have the image name `nicolargo/glances`.
* Bug fix: yes
> Fix missing docker image name

- glances/attribute.py
Prevents pop from an empty list when history_max_size is zero.
The error was introduced in bd6e682a .
* Bug fix
Setting
```
history_size=0
```
in `glances.conf` caused
```
File "/Users/Shared/src/scm/os/glances/glances/attribute.py", line 85, in value
self.history_add(self._value)
File "/Users/Shared/src/scm/os/glances/glances/attribute.py", line 110, in history_add
self._history.pop(0)
IndexError: pop from empty list
```
> Fix history_add, so it allows history_max_size to be zero

- docker-files/debian.Dockerfile
When using the latest alpine-full image the pre-packed python dependencies are in the wrong folder. This MR moves them to the correct one.
As a hotfix until the next version the images can be started with:
```bash
docker run -it nicolargo/glances:alpine-3.2.1-full bash -c 'cp -r /usr/local/python3.8/site-packages/* /usr/lib/python3.8/site-packages/ && glances -C /glances/conf/glances.conf <your glances options>'
```
or when used in a docker-compose:
```yaml
command: bash -c 'cp -r /usr/local/python3.8/site-packages/* /usr/lib/python3.8/site-packages/ && glances -C /glances/conf/glances.conf <your glances options>'
```
* Bug fix: yes
> Fix python lib path in alpine images

- docker-files/debian.Dockerfile
This adds the `smartmontools` package to the Debian based Docker image.
This package provides the `smartctl` binary which the `pySMART.smartx` package
requires.
Without this change, in the Docker container, with `--device=/dev/sda:/dev/sda` passed to `docker run`
```
Python 3.9.6 (default, Aug 17 2021, 02:38:04) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pySMART import DeviceList
>>> DeviceList()
<DeviceList contents:
>
```
With this change:
```
Python 3.9.6 (default, Aug 17 2021, 02:38:04) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pySMART import DeviceList
KeyboardInterrupt
>>> from pySMART import DeviceList
>>> DeviceList()
<DeviceList contents:
<SCSI device on /dev/sda …
```
> Update Debian image to include `smartmontools`

- glances/plugins/glances_docker.py
The IO stats for the containers on Arch Linux fail to be displayed. Reason being a small difference in responses. This PR aims to handle that.
* Bug fix: yes
* Fixed tickets: #1918 (maybe, not sure)
Assuming Ubuntu to be the standard as the stats are displays properly on it. The difference lies in the values for `blkio_stats.io_service_bytes_recursive` of the response for the Docker's container [stats API](https://docs.docker.com/engine/api/v1.41/#operation/ContainerStats). The API's example doesn't seem to document any response with the concerned field, so I ended up checking the responses. I logged the responses with a small script:
```python
import docker
client = docker.from_env()
containers = client.containers.list()
cont = containers[0]
for stats in …
```
> Fix: Docker plugin - Invalid IO stats with Arch Linux

- .github/workflows/test.yml
- README.rst
- setup.py
Python 3.10 was released on 2021-10-04:
* https://discuss.python.org/t/python-3-10-0-is-now-available/10955
In the README, let's also replace the Travis CI badge with one for GitHub Actions. 
* Bug fix: no
> Add support for Python 3.10

- glances/plugins/glances_help.py
The missing options in the help menu have been added.
A - Enable/disable Application Monitoring Process
E - Erase current process filter
K - Show/hide TCP connections
k - Kill process
M - Reset processes summary min/max
N - Show/hide current time
R - Show/hide RAID plugin
W - Show/hide Wifi module
4 - Enable/disable all but quick look and load module
* Bug fix: yes
* Fixed tickets: fixes #1973
> Added missing options to help menu

- glances/plugins/glances_cloud.py
- glances/plugins/glances_docker.py
- glances/plugins/glances_ports.py
Use is_set instead of isSet for Python 3.10 compatibility.
* Bug fix: yes
* Fixed tickets: #2017
> Use is_set instead of isSet for Python 3.10 compatibility.

- docs/aoa/header.rst
- glances/plugins/glances_ip.py
Let the Public IP address get updated every `t` seconds
The time interval can be configured by the config option under `ip` section with `public_refresh_interval`.
Default value is 300 seconds.
* Bug fix: no
* Fixed tickets: Closes #2028
> Update public ip at intervals

- unitest-restful.py
- unitest-xmlrpc.py
RESTful and XML-RPC API unitary tests should run on localhost
When you run the Glances with default binding (0.0.0.0) during the restful/xmlrpc unitary tests, starting the web server might take sometime (appx 5~30sec) depends on the host and testing may fail. I realized this when I was building the rpm package for EPEL8+9 and if you run the Glances with only loopback interface web server starts within a second. Instead of waiting subprocess with time.sleep it's better to run the tests in localhost.
* Bug fix: yes
> unitary tests should run loopback interface

- docs/aoa/amps.rst
Hi dear devs of this fine monitoring tool,
first of all thank you for this extensive documentation. I'm particularly interested in the monitoring of processes like nginx or guacamole. While reading the [AMP](https://glances.readthedocs.io/en/latest/aoa/amps.html) doc page I've noticed that there is something wrong with your link to the configuration page. This tiny PR fixes the link (by swapping stable with latest).
See reference [cross-sections](https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html#use-custom-link-text) for details.
* Bug fix: yes
> Fix reference link to configuration file in AMP

- glances/programs.py
- unitest.py
This pull requests fixes the unit tests on macOS.
In test_017_programs, the following exception may occur:
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
This commit fixes this exception by giving a default value for None.
* Bug fix: yes
> fix: fix unit testing on macOS

- .github/workflows/codeql-analysis.yml
The version 1 of CodeQL Actions is deprecrated on December 7th, 2022.
'Warning: CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/'
Upgrading the GitHub Action to the version 2 
* Bug fix: no
> chore(ci) : upgrade CodeQL Actions to version 2

- docs/gw/prometheus.rst
Add a note to the Prometheus Exporter documentation about using `host=0.0.0.0` in the `glances.conf` file otherwise, it will not work.
* Bug fix: no
* Resolves #2087
> Add note about `host` for Prometheus exporter in a container

- requirements.txt
There are 1 security vulnerabilities found in psutil 5.3.0
- [CVE-2019-18874](https://www.oscs1024.com/hd/CVE-2019-18874)
Upgrade psutil from 5.3.0 to 5.6.7 for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
> fix(sec): upgrade psutil to 5.6.7

- glances/secure.py
I want to execute shell commands in an action. Those commands are currently split by space character for security reasons (to me it's not clear why this required, but there are probably good reasons to do that ;)). As I would like to pass strings of multipel words to my commands, we have to consider quotes in command arguments.
One simple use case is the following action:
```
send_mail.sh "this is my subject" "and this is my alert text"
```
* Bug fix: yes
> Consider quotes when splitting command arguments

- setup.py
also update psutil version constraint
relates to https://github.com/Homebrew/homebrew-core/pull/120603
Update install requires so that dependency updates can be inferred on the homebrew side (see linked PR)
> setup: include ujson as required dependency

- glances/secure.py
Extension of https://github.com/nicolargo/glances/pull/2239: For quoted command arguments we have to strip surrounding quotes when creating the subprocess.
I tested the previous PR only outside glances and therefore didn't notice that behavior. Sorry for that!
* Bug fix: yes
> Remove surrounding quotes for quoted command arguments

- glances/plugins/glances_fs.py
Remove duplicate entries in the `FILE SYS` list. For some reason ZFS datasets are shown more than once, this removes the duplicate entries and filters them by `mnt_point`.
Before:
```console
FILE SYS                 Used  Total
/                        351G  1.79T
/boot (nvme0n1p1)       20.5M   511M
/mnt/Data/Backup         375G  4.73T
/mnt/Data/Backup         375G  4.73T
/mnt/Data/Deluge        2.25M  4.36T
/mnt/Data/Deluge        2.25M  4.36T
/mnt/Data/Snapshots      256K  4.36T
/mnt/Data/Snapshots      256K  4.36T
_iners/storage/overlay   351G  1.79T
```
After:
```console
FILE SYS                 Used  Total
/                        351G  1.79T
/boot (nvme0n1p1)       20.5M   511M
/mnt/Data/Backup         375G  4.73T
/mnt/Data/Deluge        2.25M  4.36T
/mnt/Data/Snapshots      256K …
```
> Make filesystem list unique

- glances/plugins/glances_processlist.py
Handling line endings and tab characters to not break UI
* Bug fix: yes
Fixes: #2337 
@nicolargo 
How about escaping `\n` to `\\n` (similarly for `\r\n` and `\t`) instead of replacing them with a space so that they will get displayed on the UI? 
One issue with this is that we could get processes with just line endings like:
`executable\narg1\narg2\narg3`
But we could maybe add a space along with the escapes to make it look like:
`executable \narg1 \narg2 \narg3`
What are your thoughts on this?
> Handle tabs in process arguments

- docker-files/alpine.Dockerfile
- optional-requirements.txt
Fix Alpine build failure for cryptography
Creating a PR to test the build without pushing to master
Fixes: #2368
> Fix alpine ARM image builds failures due to cryptography dependency

- .dockerignore
- docker-files/alpine.Dockerfile
- docker-files/ubuntu.Dockerfile
- docs/docker.rst
@nicolargo 
I've tried to make the docker builds more cleaner. 
PTAL. Changes still need to be reviewed.
Couple of Questions
1. Why is are the non-dev tags being built off the glances being pulled from pypi?
2. Why is the nvidia/cuda image used for the ubuntu images?
3. Why was a custom pip mirror used for the ubuntu builds? (mirrors.aliyun.com)
Notable difference from the original process:
- Build dependencies are no longer present in final images
- Glances is installed directly from the source code rather than from pypi
- glances built and run on a venv installed on the container
I've pushed the built images for dev on dockerhub for ref: https://hub.docker.com/r/razcrimson/glances/tags
The images seem to be running fine for now. Not all plugins were tested, but there shouldn't be any …
> chg: Dockerfile - structured & cleaner build process

- .dockerignore
- docker-bin.sh
- docker-files/alpine.Dockerfile
- docker-files/ubuntu.Dockerfile
This PR aims to add the `glances` binary back, as well as prepend `/venv/bin/` to the PATH.
* Bug fix: yes
* Fixed tickets: #2406, #2418
> Draft: Add glances binary to '/usr/local/bin' + Update ENV PATH to include '/venv/bin' in Dockerfiles

- docker-bin.sh
This PR aims to add double quotes around `$@` in the [docker-bin.sh](https://github.com/nicolargo/glances/blob/develop/docker-bin.sh) script (which I introduced in https://github.com/nicolargo/glances/pull/2419) to prevent globbing and word splitting.
For more information, see: https://www.shellcheck.net/wiki/SC2068
*To be fair, I can't think of a particular case where globbing and word splitting could have been an issue with `glances` but it doesn't hurt having a properly syntaxed/written script :smile:*
* Bug fix: yes *(kinda)*
> Double quote array expansions to avoid re-splitting elements in docker-bin.sh

- docs/docker.rst
Closes: #2439
Include the volume mounting info for OS Release to get glances on docker displaying host info.
Presenting the image variants in a table as I think it would make it easier to compare them.
> Docs: docker - include OS Release Volume mount info

- .github/workflows/build.yml
The support for arm/v6 was dropped since the build was based on python, which did not have support for arm/v6, but now they are based on alpine.
I tried running glances using docker on my raaspberry pi zero but it wouldn't start. Digged through some old issues and found that support for arm/v6 was dropped some time ago. But I think it should be fine to add it back now.O
* Bug fix: no
> Readd support for arm/v6 to docker image

- docs/docker.rst
`latest-alpine` tag is decrepated, so updating the compose example to use `latest` instead
* Bug fix: no
> Update docker.rst to remove latest-alpine tag

- docs/docker.rst
Reverts nicolargo/glances#2563 because it is done on the master branch, not the develop branch...
> Revert "Update docker.rst to remove latest-alpine tag"

- docs/config.rst
- docs/man/glances.1
- glances/config.py
Fixes nicolargo/glances#2636
To allow following the `~/.config` convention.
* Bug fix: no
* Fixed tickets: #2636
> macOS: default to `~/.config/glances`

- docs/gw/prometheus.rst
Incorrect usage of argument and minor grammatical error --export-prometheus was used instead of --export prometheus
Description
Resume
Bug fix: no
New feature: no
Fixed tickets:
> Update prometheus.rst, fix minor typos

- README.rst
- docs/aoa/gpu.rst
- glances/plugins/gpu/__init__.py
- optional-requirements.txt
- setup.py
`py3nvml` hasn't been updated for 3 years, meanwhile https://pypi.org/project/nvidia-ml-py/ appears to be directly published by nvidia and actively maintained.
* Bug fix: no
> Replace `py3nvml` with `nvidia-ml-py`

- conf/glances.conf
- docker-compose/glances.conf
- docs/config.rst
- docs/man/glances.1
- glances/main.py
- glances/outputs/glances_curses.py
- glances/plugins/help/__init__.py
This makes glances use the normal terminal color for most text, instead of an explicit 'black' or 'white' color that may not be visible.
* Bug fix: yes
* Fixed tickets: #2387 
This even supports dynamic changing terminal colorschemes without any restart, like a terminal switching from 'light' to 'dark' mode at sunset.
> Use normal color for normal text instead of an arbitrary color

- docker-compose/glances.conf
- glances/exports/mqtt/__init__.py
Due to the recent update of paho-mqtt to version V2.0.0 which requires API versioning, I added callback_api_version VERSION2 in paho.Client to warn of future removal of VERSION1
When installing paho-mqtt with the command 'pip install paho-mqtt' this automatically installs the latest version (currently 2.0.0)
This caused an error when launching Glances with the --export mqtt option.
Connection to MQTT server xxx.xxx.xxx.xxx:XXXX failed with error: Client.__init__() missing 1 required positional argument: 'callback_api_version'
The workaround was to install paho-mqtt V1.X with this command 'pip install "paho-mqtt<2"
With this fix, Glances works with the new version of paho-mqtt
* Bug fix: yes
* Fixed tickets: not for the moment
> Add CallbackAPIversion for MQTT export

- docker-compose/glances.conf
- glances/exports/mqtt/__init__.py
I added the possibility of configuring the hostname of the machine in the MQTT topic.
Are you going to ask me why?
Well I have a dualboot machine. Two different operating systems but the same hardware.
But the 'socket.gethostname()' command returns a different value depending on the operating system ("DESKTOP-B1JV0TR" on Windows and "My-ubuntu" on Linux)
This has the consequence that the access path to the topic is different in my broker even though it is the same machine.
However, I need to read the information on a topic without having to modify it depending on the OS on which I started my machine.
I thought this might be useful to other people.
* Bug fix: no
* Fixed tickets: not for the moment
> Add MQTT hostname configuration

- glances/exports/mqtt/__init__.py
This fixes an issue with #2700 which results in an unsupported operand type error because an int is passed whereas paho expects an enum.
* Bug fix: yes
* Fixed tickets: 2700
> Use enum instead of int for callback API version.

- README.rst
FreeBSD has moved glances to python 3.9 so the package name has changed
```
➜  ~ pkg install py38-glances
Updating FreeBSD repository catalogue...
Fetching packagesite.pkg: 100%    7 MiB   7.5MB/s    00:01
Processing entries: 100%
FreeBSD repository update completed. 34067 packages processed.
All repositories are up to date.
pkg: No packages available to install matching 'py38-glances' have been found in the repositories
➜  ~ pkg search glances
py39-glances-3.3.1_1           CLI curses based monitoring tool for GNU/Linux and BSD OS
➜  ~ pkg install py39-glances
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
pkg: gio-fam-backend has a missing dependency: perl
The following 6 package(s) will be affected (of 0 checked):
New …
```
> Update README.rst for FreeBSD install instructions

- glances/plugins/alert/__init__.py
> fix: plugin (alert) - pytz not working with time.tzname for some timezones

- setup.py
While [upgrading glances formula to 4.0.0](https://github.com/Homebrew/homebrew-core/pull/171483), we found the pydantic dependency missing (caused runtime failure). This PR is adding it into the setup.py for pypi artifact.
* Bug fix: yes
---
- https://github.com/Homebrew/homebrew-core/pull/171483
> fix(setup): add missing pydantic

- glances/outputs/glances_restful_api.py
> fix: RESTful API - HEAD request not supported on `{version}/status` as mentioned in docs

- glances/outputs/glances_unicode.py
This PR ***partly*** fixes #2866 and #2817 for `iTerm`, but not `kitty`. Not sure what the best course of action is, help appreciated.
Currently, the char `U+23AF` _"Horizontal Line Extension"_ is used for rendering the horizontal divider lines `MEDIUM_LINE` [(glances_unicode.py#L18)](`MEDIUM_LINE`) in `separator_line()` [glances_curses.py#L441-L455](`separator_line()`)
This char belongs to the _Miscellaneous Technical_ block, as indicated in the following PDF from The Unicode Consortium:
<div align="center">
</div>
The PR favors `─` (U+2500) from the _Box Drawing_ `[2500-257F]` block, which better suited for this purpose and more widely supported across fonts and terminal emulators.
Alternatively, _em dash_ `—` (U+2014) and _horizontal bar_ `―` (U+2015), from _General Punctuation_ …
> Replace `U+23AF` with `U+2500`

- glances/outputs/glances_curses.py
Finally solves #2817, #2866 and fixes #2876 for [Kitty](https://sw.kovidgoyal.net/kitty/) and other terminals. Related: #2867.
The bug was also present in [Alacritty](https://alacritty.org/), [Contour](https://contour-terminal.org/) and [Rio](https://raphamorim.io/rio).
Ensures `ncurses` proper line drawing, by using `self.term_window.hline()` and `curses.ACS_HLINE`. These functions are more correct and prevent drawing bugs, as suggested by Kitty's terminal maintainer, see: https://github.com/kovidgoyal/kitty/issues/7622.
* Bug fix: yes
* Fixed tickets: #2817, #2866 and #2876
- ✅ alacritty `v0.13.2`
- ✅ archipelago `v6.0.7`
- ✅ contour `v0.4.3.6442`
- ✅ cool-retro-term `v1.2.0`
- ✅ edex-ui `v2.2.8`
- ✅ electerm `v1.39.76`
- ✅ fig `v2.19.0`
- ✅ hyper `v3.4.1`
- ✅ iterm2 …
> fix: Use `ncurses` dedicated functions for the separator line

- Makefile
Part of #2906.
* Renamed variables in `Makefile`
* rules targetting `docker-*` are now built at runtime: `make help` is unchanged.
> Renamed variables in `Makefile`; rules targetting `docker-*` are now built at runtime

- Makefile
Part of #2906.
* `venv-*-python` relies on the pattern `venv-%-python`
* `venv-(full|min|dev)` & `venv-*-upgrade` on `venv-%`
* macros `UPGRADE`, `PRE_COMMIT`, `VIRTUAL_ENV`, & `REQS` are rule switches
* `VIRTUAL_ENV` being evaluated at runtime from `DEFINE_VARS_FOR_TYPE`
* `make help` is unchanged.
```shell
virtualenv -p /usr/bin/python3 venv
virtualenv -p /usr/bin/python3 venv-min
virtualenv -p /usr/bin/python3 venv-dev
venv/bin/pip install  -r requirements.txt;  venv/bin/pip install  -r optional-requirements.txt;
venv-min/bin/pip install  -r requirements.txt;
venv-dev/bin/pip install  -r dev-requirements.txt;  venv-dev/bin/pip install  -r doc-requirements.txt;
venv-dev/bin/pre-commit install --hook-type pre-commit
virtualenv -p /usr/bin/python3 venv
virtualenv -p /usr/bin/python3 …
```
> Used patterns for rules targetting `venv`, `venv-python`, `venv-upgrade`

- glances/outputs/glances_curses.py
* reverted commit 01823df917b3e51a3567698e35a9624e754f1092
* that commit introduced #2949.
* part of #2801.
Refactorized [`_GlancesCurses.display_plugin()`](https://scrutinizer-ci.com/g/nicolargo/glances/code-structure/develop/py-function/glances.outputs.glances_curses._GlancesCurses.display_plugin) version 2. Broken down using:
1. `setup_upper_left_pos`
2. `get_next_x_and_x_max`
3. `display_stats_with_current_size`
4. `display_stats`
> Refactorized `_GlancesCurses.display_plugin()`, version 2

- Makefile
Refactored `webui*` rules
* part of #2906
* output is unchanged.
```shell
commit f2f97e2f (HEAD -> makefile)
Author: Ariel Otilibili <otilibil@eurecom.fr>
Refactored `webui*` rules
0
0
0
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
commit 24c87253 (HEAD -> develop, origin/develop, origin/HEAD)
Merge: 42af55b3 fa7fc5bd
Author: Nicolas Hennion <nicolashennion@gmail.com>
Merge pull request #2941 from ariel-anieli/refactor-alert
0
0
0
0
```
> Refactored `webui*` rules

- glances/plugins/ports/__init__.py
- sequel of cbd166bf0baef31650f67cda4f357c8f4de38064; part of #2801
- tests are passing:
```shell
OK
OK
OK
```
* `get_web_alert` & `get_ports_alert` rely on `get_p_alert`
* each needs an helper: if `get_web_alert`, the helper is `get_conds_if_url`
* if `get_ports_alert`, it is `get_conds_if_port`
* `get_p_alert` uses the helper with `get_default_ret_value`.
> Reduced `get_web_alert` & `get_ports_alert`

- glances/exports/glances_mqtt/__init__.py
Addition of the 'availability' topic: Online or Offline when using the --export MQTT option in the case where other devices on the same broker are looking for our Glances instance
* Bug fix: no
> Add 'Availability' topic to MQTT connection

- glances/plugins/ip/__init__.py
Follows from #2997; closed by mistake.
```shell
OK
OK
OK
```
After:
Before:
* part of #2801
* formatted into a dict; if input method is SNMP, returns default stats
* if input method is local, calls `get_stats_for_local_input`
* it has three steps:  `get_private_ipv4`, `get_first_ipv4`, `get_public_ipv4`.
> Refactored `glances.plugins.ip.PluginModel.update`

- glances/plugins/gpu/cards/nvidia.py
Fix regression in gpu module on Windows introduced in https://github.com/nicolargo/glances/commit/49d15b20dacf6a0fdf5931573f736782234f2a85 by adding additional handling for Windows. Same approach taken as in https://github.com/gpuopenanalytics/pynvml/blob/master/pynvml/nvml.py#L1787.
* Bug fix: yes
* Fixed tickets: n/a
> add comparable NVML_LIB check for Windows

- .github/workflows/test.yml
- README.rst
- glances/outputs/glances_restful_api.py
- glances/plugins/gpu/cards/nvidia.py
- pyproject.toml
- tox.ini
Bumped minimal Python version to 3.9
* Python 3.8 is now [end of life](https://devguide.python.org/versions/)
* so doing, removed unused branch in `glances/outputs/glances_restful_api.py`
* branch introduced by f6545580dbd7e35174e7bda634a6be2b49030e56
* ruff also needs a bump; i.e, `s/py38/py39/`
* not done yet, since it needs to clear out warnings.
> Bumped minimal Python version to 3.9

- glances/cpu_percent.py
- glances/globals.py
- glances/plugins/containers/__init__.py
- glances/plugins/containers/engines/__init__.py
- glances/plugins/containers/engines/docker.py
- glances/plugins/containers/engines/podman.py
- glances/plugins/sensors/__init__.py
- glances/plugins/vms/__init__.py
- glances/plugins/vms/engines/__init__.py
- glances/plugins/vms/engines/multipass.py
- pyproject.toml
* sequel of b537f454c13041a6208bc5f54f57fd953d0f35bc
* prelude to subsequent [changes due to ruff](https://docs.astral.sh/ruff/rules/non-pep585-annotation/).
* Bumped ruff to Python 3.9
* `make lint` to clear out warnings.
> Bump ruff target to Python 3.9

- unittest-core.py
* reverting 98e8e32457dcf6129c8c6084e03675268ac20f9f
* introduced #3040.
* Bug fix: yes
> Revert "Reduced complexity of `unittest-core.TestGlances._common_plugin_tests()`"

- docs/config.rst
- docs/man/glances.1
- glances/config.py
Non-venv default config path was `/usr/share/doc/glances.conf` instead of `/usr/share/doc/glances/glances.conf` since a55970a.
Fix it and place the venv path to the end of the paths list, so it will have priority over the system default.
By the way, I'm not sure if we need to keep system default config path in venv, then we can delete `get_base_prefix_compat()` and `in_virtualenv()` functions, since they only check for sys.base_prefix != sys.prefix, and sys.prefix will point to venv when inside it and to `/usr` when outside
Also fixed some typos in docs on the way
* Bug fix: yes
> default_config_dir: Fix config path to include glances/ directory

- glances/__init__.py
Part of #2801: `start` is split into `start_main_loop`, `check_memleak`, `setup_server_mode`, & `maybe_trace_memleak`.
Before:
After:
* Bug fix: no
> glances: refactor start()

- glances/password.py
This simply fixes a small issue with password files, which can contain unsupported line endings depending on how they were created/edited. 
* Bug fix: yes
Related to Issue/#2268
https://github.com/nicolargo/glances/issues/2268
Converted to Discussion/#2274
Comment of the behavior by Kankaristo:
https://github.com/nicolargo/glances/discussions/2274#discussioncomment-12500492
> Ignore unsupported line endings in password file

- docs/aoa/smart.rst
Revision of confusing descriptions in the SMART section of the document.
`https://glances.readthedocs.io/en/latest/aoa/smart.html`
The description of `show=` in the SMART chapter of the original document may easily lead to misunderstandings among users. They might think that this setting can display only certain contents from the SMART attributes, such as temperature. However, in reality, this configuration is only effective for the specified drive, meaning it only shows information related to that specific drive.
* Bug fix: no
> Revision of confusing descriptions in the SMART section of the document

- glances/plugins/fs/__init__.py
- glances/plugins/plugin/model.py
Both GlancesPluginModel.is_hide and GlancesPluginModel.is_show has very bad case-insentitive regex matching implementation, and fs module has a double check on both mount point and device name that most of the time results in 0 match.
* Bug fix: yes
> Fix matching problem when fs config has "show" value

- glances/plugins/connections/__init__.py
Reverts nicolargo/glances#3161
Because it breaks the unittest on MacOS: https://github.com/nicolargo/glances/actions/runs/14692345739/job/41229404619#logs
> Revert "plugins: connections: refactor"

- glances/plugins/containers/__init__.py
- glances/processes.py
Refactor `sort_docker_stats()` and `sort_stats()`, then fix sorting of containers.
After:
Before:
```shell
venv/bin/python -m pytest tests/test_core.py
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.10.12, pytest-8.3.5, pluggy-1.5.0
rootdir: /home/ariel/src/glances
configfile: pyproject.toml
plugins: anyio-4.9.0
collected 37 items                                                                                                                                                                          
tests/test_core.py ..................................... …
```
> Fix the sorting of containers

- glances/plugins/containers/engines/docker.py
- glances/plugins/containers/engines/podman.py
No more needed in Python 3. Related to #3181.
* Bug fix: no
> podman: docker: Remove iterator helpers

- glances/globals.py
`namedtuple_to_dict` loops over [a dynamic view](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects
) of the dict of processes; other threads might be editing the same dict.
For instance in webserver mode, when a race condition happens, the following error shows up in the console:
```
File "C:\Users\ryabtsev\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\glances\processes.py", line 628, in update_list
return list_of_namedtuple_to_list_of_dict(processlist)
File "C:\Users\ryabtsev\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\glances\globals.py", line 495, in list_of_namedtuple_to_list_of_dict
return …
```
> globals: Fix a race condition in `namedtuple_to_dict`

- docs/aoa/network.rst
Fix labeling error
diskio label instead of network label in documentation.
* Bug fix: no
* Fixed tickets: n/a
> Label error in docs

- glances/exports/export.py
- glances/exports/glances_prometheus/__init__.py
Using proper labels for prometheus metrics of specific plugins (amps, containers, diskio, fs, gpu, network, percpu, sensors, wifi) instead of exporting each individual object as it's own metric which is both hard to use and against prometheus best-practices.
For example, before this PR we exported the following FS metrics:
`glances_fs__etc_hostname_free{hostname="HOSTNAME"}` 
This PR changes this metrics to
`glances_fs_free{hostname="HOSTNAME",mnt_point="/etc/hostname"}`
The used labels are the return value of each plugin's `get_key()`. 
At the moment these are:
- amps: name
- containers: name
- diskio: disk_name
- fs: mnt_point
- gpu: gpu_id
- network: interface_name
- percpu: cpu_number
- sensors: label
- wifi: ssid
* Bug fix: yes
* Fixed tickets: #3166
> Fix prometheus export format
